language: ruby

rvm:
  - 2.1.2

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - CODECLIMATE_REPO_TOKEN=ab1d5e4b664525c4bedee2008cef157c7e71a7fbe1c28cc529ba71aa4eb56fdb bundle exec rake

services: postgresql

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database digifoos_test;' -U postgres