development:
  adapter: postgresql
  encoding: unicode
  database: digifoos_dev
  pool: 5
  username: kobe
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: digifoos_test
  pool: 5
  username: kobe
  password: