development:
  adapter: postgresql
  encoding: unicode
  database: digifoos_dev
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: digifoos_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: digifoos_prod
  pool: 5
  username: postgres
  password: