development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  pool: 5