module ApplicationHelper
  # extends ....................................................................
  # includes ...................................................................

  include BootstrapFlashHelper
  include FontAwesome::Rails::IconHelper

  # constants ..................................................................
  # additional config ..........................................................
  # class methods ..............................................................
  # helper methods .............................................................
  def current_group
    @current_group
  end

  # protected instance methods .................................................
  # private instance methods ...................................................
end
