module GroupsHelper
  # extends ....................................................................
  # includes ...................................................................
  # constants ..................................................................
  # additional config ..........................................................
  # class methods ..............................................................
  # helper methods .............................................................
  def player_link(player_id)
    player = @players.select{|p| p.id == player_id }.first
    link_to player.name, group_player_path(current_group, player)
  end

  # protected instance methods .................................................
  # private instance methods ...................................................
end