module GroupsHelper
  # extends ....................................................................
  # includes ...................................................................
  # constants ..................................................................
  # additional config ..........................................................
  # class methods ..............................................................
  # helper methods .............................................................
  def player_link(player_id)
    player = @players.select{|p| p.id == player_id }.first
    link_to player.name, group_player_path(current_group, player)
  end

  def goals_badge_color(game, team)
    winner_class = 'winner'
    loser_class  = 'loser'

    if game.goals_team1.to_i > game.goals_team2.to_i
      team == 1 ? winner_class : loser_class
    else
      team == 1 ? loser_class : winner_class
    end
  end

  # protected instance methods .................................................
  # private instance methods ...................................................
end