class Ability
  # extends ....................................................................
  # includes ...................................................................

  include CanCan::Ability

  # constants ..................................................................
  # additional config ..........................................................
  # class methods ..............................................................
  # instance methods ...........................................................

  def initialize(user)
    user ||= User.new # guest user (not logged in)

    can :manage, :all if user.admin?

    can :read, Session, :user_id => user.id
  end

  # protected instance methods .................................................
  # private instance methods ...................................................
end
