class Game < ActiveRecord::Base
  # extends ....................................................................
  # includes ...................................................................
  # constants ..................................................................
  STATUSES = %i[ created running finished ]

  # associations ...............................................................
  belongs_to :group
  has_many   :teams
  has_one    :user, through: :group

  enum status: STATUSES

  # scopes .....................................................................
  # validations ................................................................
  validates_presence_of :group
  validates_presence_of :status
  validate :only_one_open_game_per_group

  # callbacks ..................................................................
  # additional config ..........................................................

  # class methods ..............................................................
  # instance methods ...........................................................
  # protected instance methods .................................................
  protected

  def only_one_open_game_per_group
    if !finished? && Game.where('group_id = ? AND games.status IN (?,?) AND games.id != ?', group_id, Game.statuses[:created], Game.statuses[:running], id.to_i).any?
      errors.add(:status, 'with value :created or :running can only exist once per group')
    end
  end

  # private instance methods ...................................................
end
