class Player < ActiveRecord::Base
  # extends ....................................................................
  # includes ...................................................................
  # constants ..................................................................
  # associations ...............................................................
  belongs_to :group

  has_and_belongs_to_many :teams, -> { uniq }

  has_many :games, through: :teams

  has_one :user, through: :group

  # scopes .....................................................................
  # validations ................................................................
  validates_presence_of :name, :group
  validates_uniqueness_of :name, scope: :group

  # callbacks ..................................................................
  # additional config ..........................................................
  attr_accessor :points, :goals, :games_played

  # class methods ..............................................................
  # instance methods ...........................................................
  # protected instance methods .................................................
  # private instance methods ...................................................
end
